#!/bin/bash

# =============================================================================
# MCP Metrics - Environment Setup Script
# =============================================================================
# This script creates the .env file with required environment variables
# Run this script after cloning the repository
# =============================================================================

set -e

ENV_FILE=".env"

echo " MCP Metrics - Environment Setup"
echo "=================================="
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    read -p "  .env file already exists. Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo " Setup cancelled."
        exit 1
    fi
fi

echo " Please provide the following configuration values:"
echo "(Press Enter to use default values where available)"
echo ""

# GitHub Personal Access Token (required)
read -p " GitHub Personal Access Token (required): " GITHUB_PAT
if [ -z "$GITHUB_PAT" ]; then
    echo " GitHub PAT is required. Please create one at https://github.com/settings/tokens"
    exit 1
fi

# OpenAI API Key (optional)
read -p " OpenAI API Key (optional, for AI insights): " OPENAI_API_KEY

# Anthropic API Key (optional)
read -p " Anthropic API Key (optional, for AI insights): " ANTHROPIC_API_KEY

# Repositories to ingest
read -p " Repositories to ingest (comma-separated, e.g., owner/repo1,owner/repo2): " INGEST_REPOSITORIES

# Lookback days
read -p " Days to look back for data ingestion [default: 90]: " INGEST_LOOKBACK_DAYS
INGEST_LOOKBACK_DAYS=${INGEST_LOOKBACK_DAYS:-90}

# Database configuration (with defaults)
read -p " PostgreSQL User [default: mcp]: " POSTGRES_USER
POSTGRES_USER=${POSTGRES_USER:-mcp}

read -p " PostgreSQL Password [default: mcp_password]: " POSTGRES_PASSWORD
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mcp_password}

read -p " PostgreSQL Database [default: mcp_metrics]: " POSTGRES_DB
POSTGRES_DB=${POSTGRES_DB:-mcp_metrics}

echo ""
echo " Creating .env file..."

# Create the .env file
cat > "$ENV_FILE" << EOF
# =============================================================================
# MCP Metrics - Environment Configuration
# =============================================================================
# Generated by setup.sh on $(date)
# =============================================================================

# -----------------------------------------------------------------------------
# GitHub Configuration (Required)
# -----------------------------------------------------------------------------
# Personal Access Token with repo access
# Create one at: https://github.com/settings/tokens
GITHUB_PAT=${GITHUB_PAT}

# -----------------------------------------------------------------------------
# AI Configuration (Optional - for intelligent insights)
# -----------------------------------------------------------------------------
# OpenAI API Key - https://platform.openai.com/api-keys
OPENAI_API_KEY=${OPENAI_API_KEY}

# Anthropic API Key - https://console.anthropic.com/
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# -----------------------------------------------------------------------------
# Data Ingestion Configuration
# -----------------------------------------------------------------------------
# Comma-separated list of repositories to ingest (format: owner/repo)
INGEST_REPOSITORIES=${INGEST_REPOSITORIES}

# Number of days to look back when ingesting data
INGEST_LOOKBACK_DAYS=${INGEST_LOOKBACK_DAYS}

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

# Full database URL (constructed from above values)
DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
EOF

echo ""
echo " .env file created successfully!"
echo ""
echo " Summary:"
echo "   - GitHub PAT: ****${GITHUB_PAT: -4}"
echo "   - OpenAI API Key: ${OPENAI_API_KEY:+****${OPENAI_API_KEY: -4}}"
echo "   - Anthropic API Key: ${ANTHROPIC_API_KEY:+****${ANTHROPIC_API_KEY: -4}}"
echo "   - Repositories: ${INGEST_REPOSITORIES:-None specified}"
echo "   - Lookback Days: ${INGEST_LOOKBACK_DAYS}"
echo "   - Database: ${POSTGRES_DB}"
echo ""
echo " Setup complete! You can now run:"
echo "   cd infra && docker compose up -d"
echo ""
